### ISSUE TITLE
annoation and doc around Script or Script file

### ISSUE THREAD

**Issue by wanghaisheng** [Matamata-Animator/Matamata-Core#50]
gentle lead me here, if you got time, can you spare some to explain a little about script

**Comment by AI-Spawn** [comment]
Yeah of course. So Gentle requires a text transcript of the audio when doing phoneme alignment. This will be generated automatically using the vosk-api. However, it is possible that goal’s transcription won’t be adequate (especially since it uses the small model by default, you can download the large one from [here](https://alphacephei.com/vosk/models), this will become the default in the upcoming 4.0 release). If that’s the case, you can pass in your own transcript using the `—text` tag. 

Additionally, if you are using your own transcript you can change poses with a pose tag: `words words words [NEWPOSE] words words]`. However **this feature is currently deprecated and will be removed in 4.0**. Instead, you should use time stamps to change poses. With time stamps you change poses by specifying a time(ms) and a pose name:
```
0000 Pose1
5000 Pose2
```
The time stamps get shifted to start at the next word afterwards so you don’t need to worry about being exact.

**Comment by AI-Spawn** [comment]
I'm gonna close this issue, just lmk if you have any more questions
